### ISSUE TITLE
Seeder does not work on develop

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#147]
Expected: npm run seed runs clean, without errors.
Actual: npm run seed gives error about subtransactions not being defined.

`[2024-01-27T19:25:54.641] [ERROR] Seeder - Seeding failed TypeError: Cannot read properties of undefined (reading 'subTransactionRows')
    at TransactionSubscriber.afterInsert (C:\SudoSOS\sudosos-backend\src\subscriber\transaction-subscriber.ts:50:51)
    at async Promise.all (index 1)
    at SubjectExecutor.execute (C:\SudoSOS\sudosos-backend\src\persistence\SubjectExecutor.ts:185:17)
    at EntityPersistExecutor.execute (C:\SudoSOS\sudosos-backend\src\persistence\EntityPersistExecutor.ts:197:21)
    at async Promise.all (index 72)
    at seedTransactions (C:\SudoSOS\sudosos-backend\test\seed.ts:982:3)
    at seedDatabase (C:\SudoSOS\sudosos-backend\test\seed.ts:1406:28)
    at createApp (C:\SudoSOS\sudosos-backend\src\database\seed.ts:48:5)`

**Comment by JustSamuel** [comment]
Iirc this is about an empty transaction for which the subscriber fails. It doesn't interfere with the actual seeding. But its good to fix it anyhow,

**Comment by JustSamuel** [comment]
Should be fixed, re-open if you find that it is still not working.
